### PR TITLE
Remove unneeded `six` dependency (was used for Python 2)

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by a-detiste** [comment]
Could this be a 1.0.3 ?

**Comment by Acconut** [comment]
Thank you for this PR! Could you please describe the changes you made in a bit more detail?

**Comment by a-detiste** [comment]
Hi,

I did came up with a nice write up here: https://wiki.debian.org/Python3-six-removal

The "emergency" shifted recently on removing python3-future (things starting to break with Python 3.12),
but you already have done that in git:

https://github.com/tus/tus-py-client/commit/2256c7c4aa5132db5f8c7a0efda3409a740ee6fb

**Comment by Acconut** [comment]
Thanks for the link, your changes now make a lot more sense! I merged the latest changes from main, which fix the CI builds. This is now good to go :)

**Pull request merged**
