### PR TITLE
Remove extraneous prints

### LINKED ISSUE #17: uploader prints unconditionally
the client.uploader class unconditionally prints in upload_chunk.

I'm happy to make a PR removing this, but if you want to keep the functionality behind a flag or something I'd appreciate some input into how you would like that to work.

### PR DESCRIPTION
**Pull request by richo**
Closes #17 

Let me know if there's something else you prefer I do :)

### CODE REVIEW

**Comment by richo** [comment]
Sure, I can do that, although I have a vague concern there as well. Mostly because applications that use `logging` and have debug turned on may not expect or want (filesize / chunk size) messages printed, but I think it's a reasonable compromise. Maybe logging at debug with a named param to turn it off entirely?

I'll update this pr and you can let me know what you think :)

**Comment by richo** [comment]
@ifedapoolarewaju I added an optional `log_func` constructor param, this way people can hand in whatever logging function they like :)

lmk what you think

**Comment by ifedapoolarewaju** [comment]
LGTM, thank you for the PR!

**Comment by richo** [comment]
Thankyou! Would it be possible to cut a new release so I can pull it into my project?

**Comment by ifedapoolarewaju** [comment]
@richo is this a blocker for you? I'd prefer to add a bit more changes before doing a releasing. But please let me know if it's a major blocker for you.

**Comment by richo** [comment]
Not a huge deal, I just applied this patch to the copy in my virtualenv, but it does mean anyone who downloads my software will get a ton of messages in their console.

So, it'd be nice but it's really not a huge deal. Feel free to do it when you're ready.

**Comment by Acconut** [comment]
@ifedapoolarewaju I do releases for tusd and tus-js-client relatively often even after only few changes, so the people can easily upgrade their software. Otherwise it would take long until a new release is published and changes would not propagate so quickly. So I think a release is appropriate for this change :)

**Comment by ifedapoolarewaju** [comment]
@richo @Acconut just FYI this change has been released in version `0.2.2`

**Pull request merged**
