### PR TITLE
Don't Pin Requests to an Old Version

### PR DESCRIPTION
**Pull request by peixian**
Requests is currently pinned to an old specific version, it should be updated to be pinned at higher versions to prevent dependency resolution problems.

### CODE REVIEW

**Comment by peixian** [comment]
cc @vayam

**Comment by ifedapoolarewaju** [comment]
@peixian thank you for the PR. We probably need to have this change [here as well](https://github.com/tus/tus-py-client/blob/master/setup.py#L9-L12). Otherwise installations would still have pinned versions 🙂

**Comment by kvz** [comment]
In general I'm not thrilled about fuzzy version matching because at every build/deploy it's a bit of a surprise how the dependency landscape turns out. Even patch level version bumps can cause unforeseen problems. imho it's better to make upgrades explicit. If `request` is too old, we should pinning a new version(?) This makes every change 'followable' in our git history.

I'm not familiar with Python, so if this is already covered by some kind of tooling or generally not Python-idiomatic/causing other problems please feel free to correct me

**Comment by ifedapoolarewaju** [comment]
@kvz the case is the same for python as well, but pinning of versions is mostly advised for non-libraries. i.e Private/proprietary projects where the environment is controlled and there's certainty of no conflicts with other projects' dependencies. And it is discouraged otherwise.

So we probably should unpin all the dependencies we've got here. My silly mistake for pinning them in the first place 🙂

**Comment by peixian** [comment]
@ifedapoolarewaju nice catch, I didn't realize it was also in the setup.py. I've updated it to match.

**Comment by ifedapoolarewaju** [comment]
Thank you @peixian

**Comment by peixian** [comment]
@ifedapoolarewaju Hey, the version in https://pypi.python.org/pypi/tuspy/0.1 doesn't have this PR in it, can you pop a release into pypi? Thanks!

**Comment by ifedapoolarewaju** [comment]
@peixian done deed! 👍

**Pull request merged**
